
// Fichier d'enums local pour résoudre les erreurs temporairement
// Ces enums correspondent exactement à ceux définis dans schema.prisma

export enum FilesType {
  SIGNATURE_NOMBRE_APELLIDO = "SIGNATURE_NOMBRE_APELLIDO",
  FIRMA = "FIRMA",
  NIF = "NIF", 
  NIE = "NIE",
  UNKNOWN = "UNKNOWN"
}

export enum FoldersKey {
  FICHA = "FICHA",
  DR_AYUDA = "DR_AYUDA",
  FACTURAS = "FACTURAS",
  INFORMES_FOTOGRAFICOS = "INFORMES_FOTOGRAFICOS",
  CERTIFICADO_INSTALADOR = "CERTIFICADO_INSTALADOR",
  CEEE = "CEEE",
  ACUERDO_CESION_DE_AHORROS = "ACUERDO_CESION_DE_AHORROS",
  DNI_CLIENT = "DNI_CLIENT",
  SIGNATURE = "SIGNATURE",
  PHOTOS = "PHOTOS"
}

export enum Status {
  DONNEE_RECUPEREE = "DONNEE_RECUPEREE",
  INITIALISATION_DONE_WAITING_FOR_CEE = "INITIALISATION_DONE_WAITING_FOR_CEE",
  CEE_CREATED = "CEE_CREATED",
  CONTACTED = "CONTACTED",
  CONVERTED = "CONVERTED",
  REJECTED = "REJECTED"
}
